#!/usr/bin/env python
### BEGIN INIT INFO
# Provides:          mswitch
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
"""
	Erlang-mswitch daemon control
	
	@author Jean-Lou Dupont
"""

# Customize here
name="mswitch"
# ^^^^^^^^^^^^^^


import os
import sys
import subprocess
from optparse import OptionParser

class Commands(object):
	
	cmdStart  = "erl -pa %(cmd)s -detached -sname %(name)s -run %(name)s start_link"
	cmdStop   = "escript %s_control -q stop"
	cmdStatus = "escript %s_control -q status"
	
	dostart  = "starting daemon"
	nodaemon = "cannot start daemon"
	nostop   = "cannot stop daemon"
	canstop  = "ok"
	
	# "status" field according to LSB-Core-generic specification
	
	codes = {	0: {"msg":"ok",                "canstart": True,  "stop":canstop, "start":dostart,  "status":4  },
				1: {"msg":"unspecified error", "canstart": True,  "stop":nostop,  "start":dostart,  "status":4  }, 
				2: {"msg":"daemon found",      "canstart": False, "stop":nostop,  "start":nodaemon, "status":0 }, 
				3: {"msg":"daemon not found",  "canstart": True,  "stop":nostop,  "start":dostart,  "status":3  }, 
				4: {"msg":"library not found", "canstart": False, "stop":nostop,  "start":nodaemon, "status":4 },
				5: {"msg":"node not found",    "canstart": True,  "stop":nostop,  "start":dostart,  "status":4  },
			}
	
	def __init__(self):
		self.name = globals()["name"]
	
	def cmd_start(self, fb):
		ctx=self._canStart()
		if fb:
			print "%s: %s [%s]\n" % (self.name, ctx["start"], ctx["msg"])
		if not ctx["canstart"]:
			sys.exit(1)

		self._dostart()
		sys.exit(0)	
		
	def cmd_stop(self, feedback):
		self._dostop(feedback)
	
	def cmd_restart(self, feedback):
		self.cmd_stop(feedback)
		self.cmd_start(feedback)
		
	def cmd_reload(self, feedback):
		if feedback:
			print "%s: unimplemented feature\n" % self.name
		sys.exit(3) #unimplemented feature (see LSBInitScript documentation)
		
	def cmd_status(self, feedback):
		ctx=self._canStart()
		if feedback:
			print "%s: [%s]\n" % (self.name, ctx["msg"])
		sys.exit(ctx["status"])

	
	## =-----------------------------------------------------=- ##
	
	def _dostart(self):
	
		#add development path
		cwd=os.getcwd()
		params={"name":self.name, "cmd":cwd+"/ebin"}
		cmd=self.cmdStart % params
		proc = subprocess.Popen(cmd, shell=True)
		return proc.wait()
		
	def _dostop(self, fb):
		proc = subprocess.Popen(self.cmdStop % self.name, shell=True)
		proc.wait()
		ret=proc.returncode
		ctx=self._getCtx(ret)
		if fb:
			print "%s: %s [%s]\n" % (name, ctx["stop"], ctx["msg"])

	def _getCtx(self, code):
		ctx=self.codes.get(code, self.codes[1])
		return ctx			

	def _canStart(self):
		proc = subprocess.Popen(self.cmdStatus % self.name, shell=True)
		proc.wait()
		ret=proc.returncode
		ctx=self._getCtx(ret)
		return ctx
		
	

def main():
	usage= """%s [-q] [start|stop] 
""" % name
	
	parser=OptionParser(usage)
	parser.add_option("-q", "--quiet",
                  action="store_false", dest="feedback", default=True,
                  help="don't print status messages to stdout")
                  
	(options, args) = parser.parse_args()
    
	if len(args) != 1:
		parser.error("incorrect number of arguments")
      
	cmd = args[0]
	feedback = options.feedback
	
	try:
		getattr(Commands(), "cmd_"+cmd)(feedback)
	except Exception, e:
		print "Exception [%s]\n" % e
		print "! invalid command [%s]\n" % cmd

	
if __name__=="__main__":
	main()
